name: Airflow ETL CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover tests

    - name: Build Docker image
      run: docker build -t airflow-etl:${{ github.sha }} .

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker tag airflow-etl:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/airflow-etl:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/airflow-etl:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to production
      run: |
        echo "Add your deployment steps here"
        # For example:
        # - SSH into your server
        # - Pull the latest Docker image
        # - Stop the old container and start a new one
